### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by fproldan** [gsterjov/angular-tasty-resource#2]
Hi, thanks for this module. 
My question is, how can i work with the pagination that tastypie provides?

Thanks

**Comment by gsterjov** [comment]
To be honest I haven't tried pagination with tastypie yet. But it should be prety simple to extend TastyResource for that purpose.

**Comment by andresriancho** [comment]
@fproldan did you finally implement the pagination feature? I'm using angular-tasty-resource for a project and we're needing pagination. Would love to just re-use your code :+1: 

If it's not implemented I can do it and send a pull-request

**Comment by nim4n** [comment]
any news about pagination?

**Comment by andresriancho** [comment]
Well, after playing with this for a while I believe there is almost no need to add code, you can simply run:

``` javascript
$scope.users = User.query({'limit': 20, 'offset': 20});
```

To get the second page, and:

``` javascript
$scope.users = User.query({'limit': 20, 'offset': 40});
```

To get the third.

**Comment by fproldan** [comment]
@andresriancho  Sorry for the delay. I finally don't use pagination, instead i increment the 'limit'. For access to another pages you can use the 'offset' as you pointed, or the "nex'  and 'previus' in meta.

``` javascript
meta: {
limit: 2,
next: "/api/v1/foo/?limit=2&offset=2",
offset: 0,
previous: null,
total_count: 13
},
```

**Comment by nim4n** [comment]
tnx , I want to show how many page I have in a view so how can I get total_count ?
is there any way to get meta detail from your api?

**Comment by fproldan** [comment]
Hi, if in your controller have:

``` javascript
$scope.foo = Foo.query();
```

In html you can access:

``` html
<p>Total results: {{foo.meta.total_count}}</p>
<p>Limit per page: {{{foo.meta.limit}}</p>
```

So, i guess you can do foo.meta.total_count / foo.meta.limit, and then you can do a kind of round.

Sorry for my english.

**Comment by nim4n** [comment]
tnx alot It works! the problem was I check value of meta just after query and It didn't define!

**Comment by gsterjov** [comment]
I'm late into this conversation but having pagination in there could abstract away all the digging around with meta and offsets. It would be nice having a .pages.next() or .pages.total. It might break the api though so it should be configurable or determined with a new parameter
